const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/vicga/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');let browser;
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const context=await browser.newContext({viewport:{width:1366,height:768}}),page=await context.newPage(),checks=[],errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>requests.push(r.url()));
 const check=(name,ok=true)=>{assert(ok,name);checks.push(name);console.log('PASS',name)},state=()=>page.evaluate(()=>window.__museum.getState());
 await page.goto('http://localhost:4176/');await page.waitForFunction(()=>window.__museum?.molecule.model&&document.querySelector('#loading').hidden);await page.screenshot({path:'evidence/01-inicio-1366.png'});
 await page.locator('.large[data-action="start"]').click();check('786 residuos locales',await page.evaluate(()=>window.__museum.molecule.atoms({atom:'CA'}).length===786));await page.screenshot({path:'evidence/02-sala-1366.png'});
 await page.locator('[data-station="1"]').click();await page.locator('#jump-residue').fill('786');await page.locator('[data-action="jump"]').click();check('Selección de última posición',(await state()).selected==='A786');check('Numeración procesada', (await page.locator('#residue-card').innerText()).includes('760'));
 await page.locator('[data-org="binary"]').click();await page.waitForFunction(()=>window.__museum.getState().organization==='binary');check('Vista sin señal',await page.locator('#view-label').innerText().then(t=>t.includes('27–786')));
 await page.locator('[data-station="3"]').click();await page.locator('[data-build="3"]').click();check('Rechaza hexámero',(await state()).gameDone.length===0);for(const i of [0,1,2])await page.locator(`[data-build="${i}"]`).click();check('Reto de red completado',(await state()).gameDone.length===3);await page.locator('[data-build="0"]').click();check('Evita duplicados',(await state()).gameDone.length===3);
 await page.locator('[data-station="4"]').click();await page.locator('#stretch').fill('0.8');check('Estiramiento aplicado',(await state()).network.extension===.8);await page.locator('[data-action="release"]').click();await page.waitForTimeout(750);check('Recuperación íntegra',(await state()).network.extension===0);await page.locator('[data-quiz="0"]').click();check('Reto elasticidad', (await page.locator('#quiz-feedback').innerText()).includes('Correcto'));
 await page.locator('[data-action="compare"]').click();check('Comparación visible',await page.locator('#compare').isVisible());await page.screenshot({path:'evidence/03-comparacion-1366.png'});await page.locator('[data-action="compare"]').click();
 await page.locator('[data-station="7"]').click();await page.locator('[data-condition="proteolysis"]').click();await page.locator('#stretch').fill('0.7');await page.locator('[data-action="release"]').click();check('Soltar no repara proteólisis',(await state()).network.condition==='proteolysis'&&(await state()).network.extension===.7);await page.locator('[data-damage-answer="0"]').click();check('Diferencia desnaturalización y degradación',(await page.locator('#damage-feedback').innerText()).includes('Correcto'));await page.screenshot({path:'evidence/04-integridad-1366.png'});
 await page.locator('[data-station="8"]').click();await page.locator('[data-step="3"]').click();check('Rechaza paso prematuro',(await state()).pathway.length===0);for(let i=0;i<6;i++)await page.locator(`[data-step="${i}"]`).click();check('Reto MeTro completo',(await state()).pathway.length===6);await page.screenshot({path:'evidence/05-metro-1366.png'});
 await page.keyboard.press('Control+Shift+E');check('Expositor con cinco preguntas',await page.locator('#modal details').count()===5);await page.keyboard.press('Escape');
 await page.locator('[data-station="0"]').click();await page.locator('[data-action="reset-view"]').click();const before=await page.evaluate(()=>window.__museum.molecule.viewer.getView());await page.keyboard.press('d');check('Teclado rota',JSON.stringify(before)!==JSON.stringify(await page.evaluate(()=>window.__museum.molecule.viewer.getView())));
 await page.locator('[data-action="settings"]').click();await page.locator('[data-action="diagnostics"]').click();await page.locator('[data-action="simulate"]').click();await page.locator('[data-axis="0"]').fill('0.8');await page.waitForTimeout(600);check('Diagnóstico simulador', (await page.locator('#diag-live').innerText()).includes('activo'));await page.locator('[data-action="neutral"]').click();await page.keyboard.press('Escape');
 for(let i=0;i<3;i++){await page.locator('[data-action="restart"]').click();await page.waitForFunction(()=>!window.__museum.getState().started);check(`Reinicio ${i+1}`,(await state()).gameDone.length===0&&(await state()).pathway.length===0);await page.locator('.large[data-action="start"]').click();}
 await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:'evidence/06-sala-1920.png'});check('Sin desbordamiento a 1920',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:1366,height:768});check('Sin desbordamiento a 1366',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>window.__museum?.molecule.model&&document.querySelector('#loading').hidden);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.__museum?.molecule.model&&document.querySelector('#loading').hidden);check('PWA recarga sin red',await page.evaluate(()=>navigator.serviceWorker.controller!==null));await page.locator('.large[data-action="start"]').click();await page.locator('[data-station="7"]').click();check('Integridad disponible sin red',await page.locator('[data-condition="proteolysis"]').isVisible());
 check('Sin solicitudes externas obligatorias',requests.every(u=>u.startsWith('http://localhost:4176/')||u.startsWith('data:')));check('Sin errores de consola',errors.length===0);
 fs.writeFileSync('evidence/e2e-results.json',JSON.stringify({checks,errors,externalRequests:requests.filter(u=>!u.startsWith('http://localhost:4176/')),physicalGamepad:false,offline:'browser network disabled'},null,2));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});

