import './style.css';
import {conditionDescriptions,damageQuestion,type NetworkCondition} from './damage';
import {enabledProteins,rooms,aminoAcids} from './proteins';
import {Molecule} from './molecule';
import {MuseumClock,buttonMap,deadzone,smooth,parseResidue,toggleOrganization,missingResources,validateProtein,clamp} from './core';
import type {Organization,Representation,ResidueId} from './types';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const protein=enabledProteins.find(p=>p.id===new URLSearchParams(location.search).get('sala'))||enabledProteins[0];
const app=$('#app');
document.body.classList.add('at-home');
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
app.innerHTML=`
 <header><button class="brand" data-action="home" aria-label="Volver a las salas"><span class="brandmark">◈</span><span>MUSEO INTERACTIVO<small>DE PROTEÍNAS</small></span></button><div class="room-title"><span class="live-dot"></span>SALA ${String(rooms.findIndex(r=>r.id===protein.id)+1).padStart(2,'0')} <b>${protein.name}</b></div><div class="header-actions"><span id="offline-state" class="status">RECURSOS LOCALES</span><button data-action="sound" id="sound" aria-label="Activar sonido">♪ Audio</button><button data-action="help">Controles</button><button data-action="settings" aria-label="Abrir ajustes">⚙</button><button data-action="fullscreen" aria-label="Pantalla completa">⛶</button></div></header>
 <main class="museum">
 <nav class="station-nav" aria-label="Estaciones">${protein.stations.map((s,i)=>`<button data-station="${i}" title="${s.kicker}" aria-label="${s.kicker}"><span>${String(i+1).padStart(2,'0')}</span><small>${['Identidad','Secuencia','Estructura','Conecta','Elasticidad','Química','Interacción','Integridad','Biomaterial'][i]}</small></button>`).join('')}</nav>
 <section class="stage" aria-label="Visor molecular interactivo">
 <div class="stage-top"><div><span class="eyebrow">EXPLORADOR MOLECULAR</span><h2 id="model-title">${protein.name} <small>/ ${protein.pdb}</small></h2></div><div class="segment" id="organization-buttons">${[['monomer','Precursor'],['binary','Sin señal'],['complex','Red didáctica']].map(([v,t])=>`<button data-org="${v}">${t}</button>`).join('')}</div></div>
 <div id="viewer" aria-label="Modelo 3D: arrastra para rotar y pulsa un residuo" tabindex="0"></div>
 <div id="compare" hidden><span>Red didáctica · sin coordenadas atómicas</span><div id="compare-viewer"></div></div>
 <div id="loading">Cargando coordenadas locales…</div><div class="view-label" id="view-label">PREDICCIÓN AlphaFold · confianza muy baja · NO es una fibra real</div>
 <div id="tour-banner" hidden><span id="tour-label"></span><button data-action="takeover">Tomar el control</button></div>
 <div class="stage-bottom"><div class="legend"><span class="a">● Cadena</span><span class="b">● Señal 1–26</span><span class="gold">◆ Lisinas</span></div><div class="viewer-tools"><button data-action="zoom-out" aria-label="Alejar">−</button><button data-action="reset-view" aria-label="Centrar modelo">⌖</button><button data-action="zoom-in" aria-label="Acercar">+</button><button data-action="labels" id="labels-button">Etiquetas</button></div></div>
 <div class="representations" aria-label="Representación molecular">${[['cartoon','Trazado'],['sticks','Bolas y varillas'],['surface','Superficie'],['combined','Combinada'],['bridges','Lisinas']].map(([v,t])=>`<button data-rep="${v}">${t}</button>`).join('')}</div>
 </section>
 <aside class="info-panel" aria-label="Información y actividades"><div id="station-content"></div><div id="residue-card" aria-live="polite"></div><div id="activity-content"></div><div class="panel-footer"><button data-action="details">+ Profundizar y fuentes</button><button data-action="next">Siguiente estación →</button></div></aside>
 <section class="sequence" aria-label="Explorador de secuencia"><div class="sequence-head"><div><span class="eyebrow">DE LA SECUENCIA AL ESPACIO</span><span class="sequence-hint">Selecciona un aminoácido · N → C</span></div><span class="gold">K = lisina · ◆ = grupo amino</span></div><div id="sequence-pages"></div><div id="sequence-body"></div></section>
 </main>
 <footer><span id="pad-status">◉ Mouse · teclado · táctil</span><span id="fps"></span><span id="subtitle" aria-live="polite"></span><button data-action="restart">REINICIAR PARA EL SIGUIENTE VISITANTE ↺</button></footer>
 <section id="landing" class="landing"><div class="landing-copy"><span class="eyebrow">ESTRUCTURAS BIOLÓGICAS / SALA 03</span><h1>Ceder.<br><em>Y volver.</em></h1><p>Entra en la estructura de la vida.<br>Explora la elastina y descubre cómo una red<br>devuelve la forma a nuestros tejidos.</p><button class="primary large" data-action="start">INICIAR EXPERIENCIA <span>→</span></button><div class="landing-hint">Arrastra para explorar · Selecciona para descubrir<br>También puedes usar un mando de Xbox</div></div><div class="room-cards">${rooms.map((r,i)=>`<button ${!r.enabled?'disabled':''} data-action="start"><small>SALA ${String(i+1).padStart(2,'0')}</small><strong>${r.name}</strong><span>${r.enabled?'Disponible · Explorar →':['insulin','interferon'].includes(r.id)?'Versión independiente entregada':'Por incorporar'}</span></button>`).join('')}</div><span class="landing-credit">ELASTINA HUMANA · MODELO PREDICHO ALPHAFOLD + RED DIDÁCTICA</span></section>
 <dialog id="modal"><div class="modal-head"><span class="eyebrow" id="modal-eyebrow">MUSEO INTERACTIVO DE PROTEÍNAS</span><button data-action="close" aria-label="Cerrar ventana">✕</button></div><div id="modal-body"></div></dialog>
 <div id="toast" role="status" hidden></div><div id="pause-overlay" hidden><strong>Experiencia en pausa</strong><button data-action="pause" class="primary">Reanudar</button></div>`;
const errors=validateProtein(protein);if(errors.length)throw Error(errors.join('; '));
const molecule=new Molecule($('#viewer'),protein);let comparison:Molecule|null=null;
let sequencePage=0, receptorParts:string[]=[];let damageAnswer:number|null=null, stretchObserved=false;
let station=0,level='primary',started=false,game=false,gameDone:string[]=[],firstCys:ResidueId|null=null,pathway:number[]=[],quizAnswer:number|null=null;
const clock=new MuseumClock(protein.tour.durationSeconds,protein.tour.idleSeconds);clock.last=performance.now();
let lastTour=-1,muted=true,volume=.65,labels=true,toastTimer=0,restoreFocus:HTMLElement|null=null;
const audio=new Audio();audio.volume=volume;let cues:{start:number;end:number;text:string}[]=[];let audioId='';
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let installPrompt:any=null;
let diag=false,simulating=false,simAxes=[0,0,0,0],simTriggers=[0,0],neutral=[0,0,0,0],axisSmooth=[0,0,0,0],dz=.16,calibration:number[][]=[];
let calibrating=false,pad:Gamepad|null=null,lastButtons:boolean[]=[],lastPadLabel='',frameTimes:number[]=[];
const reps:Representation[]=['cartoon','sticks','surface','combined','bridges'];
function toast(message:string){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>$('#toast').hidden=true,4200);}
function interaction(){const wasTour=clock.start!==null;clock.interact(performance.now());lastTour=-1;$('#tour-banner').hidden=true;if(wasTour){stopAudio();$('#subtitle').textContent='';}}
function sources(ids:string[]){return ids.map(id=>{const s=protein.sources.find(s=>s.id===id)!;return `<article class="source"><a href="${s.url}" target="_blank" rel="noopener">${s.title} ↗</a><p>${s.evidence}</p></article>`;}).join('');}
function openModal(html:string,title='MUSEO INTERACTIVO DE PROTEÍNAS'){interaction();restoreFocus=document.activeElement as HTMLElement;$('#modal-eyebrow').textContent=title;$('#modal-body').innerHTML=html;if(!$<HTMLDialogElement>('#modal').open)$<HTMLDialogElement>('#modal').showModal();}
function closeModal(){diag=false;simulating=false;simAxes.fill(0);simTriggers.fill(0);$<HTMLDialogElement>('#modal').close();restoreFocus?.focus();clock.interact(performance.now());}
function updateButtons(){document.querySelectorAll<HTMLButtonElement>('[data-station]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.station)===station);b.setAttribute('aria-current',Number(b.dataset.station)===station?'step':'false');});document.querySelectorAll<HTMLButtonElement>('[data-org]').forEach(b=>{b.classList.toggle('active',b.dataset.org===molecule.organization);b.setAttribute('aria-pressed',String(b.dataset.org===molecule.organization));});document.querySelectorAll<HTMLButtonElement>('[data-rep]').forEach(b=>{b.classList.toggle('active',b.dataset.rep===molecule.representation);b.setAttribute('aria-pressed',String(b.dataset.rep===molecule.representation));});$('#labels-button').setAttribute('aria-pressed',String(labels));}

function renderSequence(){const chain=protein.chains[0],from=sequencePage*33;$('#sequence-pages').innerHTML=`<button data-seqpage="${Math.max(0,sequencePage-1)}">←</button><span>${from+1}–${Math.min(from+33,chain.sequence.length)} / ${chain.sequence.length}</span><button data-seqpage="${Math.min(23,sequencePage+1)}">→</button><label>Ir a posición <input id="jump-residue" type="number" min="1" max="786" value="${from+1}"></label><button data-action="jump">Ver residuo</button>`;$('#sequence-body').innerHTML=`<div class="sequence-row"><button class="chain-tag a" data-focus="A">Cadena A<small>786 aa</small></button><div class="residues">${[...chain.sequence.slice(from,from+33)].map((aa,j)=>{const i=from+j,id=`A${i+1}`;return `<button data-residue="${id}" class="residue a ${aa==='K'?'cysteine':''} ${molecule.selected===id?'selected':''}" title="${id} · ${aminoAcids[aa][1]} (${aminoAcids[aa][0]}, ${aa})" aria-label="${id} ${aminoAcids[aa][1]}" aria-pressed="${molecule.selected===id}"><small>${i+1}</small><b>${aa}</b>${aa==='K'?'<i>◆</i>':''}</button>`;}).join('')}</div></div>`;}
function renderStation(){const s=protein.stations[station];$('#station-content').innerHTML=`<span class="eyebrow">${s.kicker}</span><h1>${s.title.replace('\n','<br>')}</h1><p class="lead">${s.text}</p>${station===0?'<div class="stats"><div><b>786</b><small>aa precursor</small></div><div><b>26</b><small>señal</small></div><div><b>760</b><small>aa procesados</small></div></div><p class="micro">Homo sapiens · ELN · P15502 canónico<br>La longitud depende de la isoforma.</p>':''}<div class="source-line">Fuente: ${s.sources.map(id=>protein.sources.find(x=>x.id===id)!.title.split(' · ')[0]).join(' / ')}</div>`;renderActivity();updateButtons();}
const networkControls=()=>molecule.organization!=='complex'?'':`<div class="inset"><label>Estiramiento didáctico <input id="stretch" type="range" min="0" max="1" step=".02" value="${molecule.network.extension}"></label><button data-action="release">Soltar la carga ↩</button><p class="micro">Sin unidades físicas: no predice la respuesta de un tejido real.</p></div>`;
function renderActivity(){let html='';
 if(station===1)html='<p class="inset">Las posiciones 1–26 son señal de secreción. Puedes ver el precursor completo o esconder la señal con «Sin señal».</p>';
 if(station===2)html=`<div class="levels">${protein.levels.filter(l=>l.applicable).map(l=>`<button class="${level===l.id?'active':''}" data-level="${l.id}">${l.title}</button>`).join('')}</div><p class="inset">${protein.levels.find(l=>l.id===level)!.text}</p><button data-action="confidence">${molecule.confidence?'Color de cadena':'Colorear por confianza pLDDT'}</button><p class="micro">pLDDT medio 35,84 · 97,7 % por debajo de 50. Esta predicción no establece contactos, hélices ni elasticidad. En el mapa, rojo = menor confianza y azul = mayor.</p>`;
 if(station===3)html=`<section class="challenge"><span class="eyebrow">RETO 01 · CONSTRUYE LA LÓGICA DE LA RED</span><h3>Elige los tres elementos <span class="progress">${gameDone.length} / 3</span></h3><p>Necesitas movilidad, grupos reactivos y la enzima que inicia la reticulación.</p><div class="answer-options">${['Regiones ricas en Gly y Pro','Lisinas con grupos amino','Lisil oxidasa (LOX)','Hexámero con zinc','Sitio activo de la elastina'].map((x,i)=>`<button data-build="${i}" class="${gameDone.includes(String(i))?'done':''}">${x}${gameDone.includes(String(i))?' ✓':''}</button>`).join('')}</div><p id="game-feedback" aria-live="polite">${gameDone.length===3?'¡Red comprendida! La movilidad y la reticulación contribuyen a la función. No acabas de simular biosíntesis.':'Selecciona los elementos apropiados.'}</p><p class="micro">Las conexiones dibujadas son simbólicas. No se asignan parejas de lisinas sin evidencia.</p><button data-action="restart-game">Reiniciar reto</button></section>`;
 if(station===4)html=`<section class="challenge"><span class="eyebrow">RETO 02 · EXPLORA Y DECIDE</span><button data-action="compare" class="wide">${comparison?'Cerrar comparación':'Precursor y red lado a lado'} ⇄</button>${networkControls()}<h3>${protein.questions[2].q}</h3><div class="answer-options">${protein.questions[2].answers.map((a,i)=>`<button data-quiz="${i}">${a}</button>`).join('')}</div><p id="quiz-feedback" aria-live="polite">${quizAnswer===null?'Estira y suelta antes de responder.':quizAnswer===0&&stretchObserved?'✓ Correcto. '+protein.questions[2].explanation:'Explora la red y vuelve a elegir.'}</p></section>`;
 if(station===5)html='<div class="inset"><button data-residue="A61">K61 · Lisina</button><button data-residue="A27">G27 · Glicina</button><button data-residue="A30">P30 · Prolina</button><p class="micro">Ejemplos químicos; no afirman una conexión específica en una fibra madura.</p></div>';
 if(station===6)html='<div class="signal-flow"><span>Tropoelastina soluble</span>↓<span>Ensamblaje sobre microfibrillas</span>↓<span>Reticulación y fibra elástica</span></div><p class="micro">Esquema conceptual. No es un complejo atómico ni una trayectoria temporal medida.</p>';
 if(station===7)html=`<div class="answer-options">${(['intact','conformational','proteolysis'] as NetworkCondition[]).map((c,i)=>`<button data-condition="${c}" class="${molecule.network.condition===c?'active':''}">${['Red íntegra','Cambio conformacional','Degradación proteolítica'][i]}</button>`).join('')}</div><p id="damage-description" class="inset">${conditionDescriptions[molecule.network.condition]}</p>${networkControls()}<p class="micro">Desnaturalización: pérdida de organización conformacional; no equivale a los cambios normales de una cadena flexible. La vista «Cambio conformacional» solo ilustra continuidad de la cadena, no un estado desnaturalizado medido.</p><h3>${damageQuestion.q}</h3><div class="answer-options">${damageQuestion.answers.map((a,i)=>`<button data-damage-answer="${i}">${a}</button>`).join('')}</div><p id="damage-feedback" aria-live="polite">${damageAnswer===null?'':(damageAnswer===0?'✓ Correcto. ':'Revisa la diferencia. ')+damageQuestion.explanation}</p>`;
 if(station===8)html=`<section class="challenge"><span class="eyebrow">RETO 03 · ORDENA EL DESARROLLO</span><h3>${protein.application.name}</h3><p class="micro">Ejemplo preclínico publicado en 2017. Selecciona los pasos en orden.</p><div class="pathway">${[0,3,1,4,2,5].map(i=>`<button data-step="${i}" class="${pathway.includes(i)?'done':''}"><b>${protein.application.steps[i].icon}</b>${protein.application.steps[i].title}${pathway.includes(i)?' ✓':''}</button>`).join('')}</div><p id="path-feedback" aria-live="polite">${pathway.length===6?'✓ Recorrido completo. Diseñar exige comprobar función mecánica y seguridad.':pathway.length?protein.application.steps[pathway.at(-1)!].text:'Empieza por la materia prima proteica.'}</p><div class="step-counter">${pathway.length} / 6 pasos</div><button data-action="path-info">Explorar el esquema completo</button></section>`;
 if(station!==4&&station!==7)html=networkControls()+html;
 $('#activity-content').innerHTML=html;
}
async function setStation(i:number,automatic=false){if(!automatic)interaction();station=(i+protein.stations.length)%protein.stations.length;const s=protein.stations[station];$('#residue-card').innerHTML='';molecule.selected=null;molecule.assemblyProgress=station===3?gameDone.length:3;if(station!==4)closeComparison();if(station!==7)molecule.network.condition='intact';if(s.organization&&molecule.organization!==s.organization)await changeOrganization(s.organization,false);molecule.focusRegion(s.focus||'');renderStation();renderSequence();$('.info-panel').scrollTop=0;if(station===2)applyLevel();if(s.audio&&!automatic)void playAudio(s.audio);else{stopAudio();$('#subtitle').textContent='';}}
async function changeOrganization(org:Organization,user=true){if(user){interaction();molecule.selected=null;$('#residue-card').innerHTML='';renderSequence();}$('#loading').hidden=false;try{await molecule.load(org);$('.representations').hidden=org==='complex';$('.legend').innerHTML=org==='complex'?'<span class=gold>━ Cadenas simbólicas · ◆ Conexiones</span>':'<span class=a>● Cadena</span><span class=b>● Señal 1–26</span><span class=gold>◆ Lisinas</span>';$('#model-title').innerHTML=org==='complex'?'Red elástica <small>/ esquema didáctico</small>':'Tropoelastina <small>/ AlphaFold v6 · predicción</small>';$('#view-label').textContent=org==='complex'?'ESQUEMA · sin escala atómica · conexiones simbólicas':`${org==='binary'?'Sin señal · posiciones 27–786':'Precursor · posiciones 1–786'} · PREDICCIÓN DE MUY BAJA CONFIANZA`;renderActivity();updateButtons();}catch(e){toast(String(e));}finally{$('#loading').hidden=true;}}
async function selectResidue(id:ResidueId,displayChain?:string){interaction();const r=parseResidue(id);if(!r||r.chain!=='A'||r.resi<1||r.resi>786)return;if(molecule.organization==='complex'||molecule.organization==='binary'&&r.resi<=26)await changeOrganization('monomer',false);sequencePage=Math.floor((r.resi-1)/33);molecule.select(id,displayChain);renderSequence();const aa=protein.chains[0].sequence[r.resi-1],[three,name]=aminoAcids[aa],atom=molecule.atoms({chain:'A',resi:r.resi,atom:'CA'})[0];$('#residue-card').innerHTML=`<div class="selected-residue"><span class="eyebrow">POSICIÓN DEL PRECURSOR</span><h3>${id} · ${name}</h3><p>${three} / ${aa} · ${r.resi<=26?'Señal de secreción':`Posición ${r.resi-26} después de retirar la señal`}</p><p>${aa==='K'?'Su amina lateral ilustra la química de las lisinas. No conocemos una pareja de reticulación para este residuo.':aa==='G'?'La glicina tiene una cadena lateral pequeña; contribuye a la diversidad conformacional.':aa==='P'?'El anillo de la prolina restringe la geometría local y puede favorecer giros.':'Forma parte de la secuencia. No se atribuye una función específica a esta posición sin evidencia.'}</p><p class="micro">pLDDT ${atom?.b.toFixed(1)??'—'} · coordenadas predichas, no experimentales.</p></div>`;}
molecule.onSelect=selectResidue;
async function startGame(){game=true;gameDone=[];molecule.assemblyProgress=0;await changeOrganization('complex',false);renderActivity();}
function applyLevel(){const l=protein.levels.find(l=>l.id===level)!;void changeOrganization(l.id==='quaternary'?'complex':'monomer',false);renderActivity();}
async function toggleCompare(){interaction();if(comparison){closeComparison();renderActivity();return;}await changeOrganization('complex',false);$('#compare').hidden=false;$('#compare>span').textContent='Precursor · AlphaFold · predicción';$('.stage').classList.add('comparing');molecule.viewer.resize();molecule.fit(.8);comparison=new Molecule($('#compare-viewer'),protein);comparison.labels=false;comparison.representation='cartoon';await comparison.load('monomer',false);comparison.fit(.8);renderActivity();}
function closeComparison(){if(comparison){comparison.dispose();comparison=null;$('#compare').hidden=true;$('.stage').classList.remove('comparing');molecule.viewer.resize();molecule.fit();}}
let audioAvailable:Record<string,boolean>={},audioRequest=0,minTourDuration=30;
function stopAudio(){audioRequest++;audio.pause();}
async function measureTour(){clock.weights=await Promise.all(protein.tour.steps.map((_,i)=>new Promise<number>(resolve=>{const item=protein.audios[`tour-${i}`];if(!audioAvailable[`tour-${i}`]){resolve(8);return;}const probe=new Audio();const timeout=window.setTimeout(()=>resolve(8),5000);probe.preload='metadata';probe.onloadedmetadata=()=>{clearTimeout(timeout);resolve(Number.isFinite(probe.duration)?probe.duration+1:8);};probe.onerror=()=>{clearTimeout(timeout);resolve(8);};probe.src=item.file;})));minTourDuration=Math.ceil(clock.weights.reduce((a,b)=>a+b,0));clock.duration=Math.max(clock.duration,minTourDuration);}
async function playAudio(id:string){const item=protein.audios[id];if(!item)return;stopAudio();const request=audioRequest;audioId=id;cues=[];$('#subtitle').textContent=(!muted||clock.start!==null)?item.text:'';if(!audioAvailable[id])return;audio.src=item.file;try{const r=await fetch(`/audio/${id}.json`);if(r.ok){const next=await r.json();if(request!==audioRequest)return;cues=next;}}catch{}if(request!==audioRequest)return;if(!muted)audio.play().catch(()=>toast('Pulsa Audio para escuchar la narración.'));}
audio.addEventListener('timeupdate',()=>{const cue=cues.find(c=>audio.currentTime>=c.start&&audio.currentTime<c.end);$('#subtitle').textContent=!audio.paused&&cue?cue.text:'';});audio.addEventListener('ended',()=>$('#subtitle').textContent='');
audio.addEventListener('error',()=>{if(!muted)toast('Narración no disponible. El contenido y los subtítulos siguen en la estación.');});
async function vibrate(){try{await (pad as any)?.vibrationActuator?.playEffect('dual-rumble',{duration:150,weakMagnitude:.35,strongMagnitude:.15});}catch{}}
function startExperience(){document.body.classList.remove('at-home');molecule.labels=labels;molecule.applyStyle();started=true;document.body.classList.remove('at-home');molecule.labels=labels;$('#landing').hidden=true;interaction();void setStation(0);molecule.viewer.resize();}
async function restart(){interaction();closeModal();clock.paused=false;clock.permanent=false;muted=true;$('#sound').textContent='♪ Audio';labels=true;$('#pause-overlay').hidden=true;game=false;gameDone=[];firstCys=null;pathway=[];damageAnswer=null;stretchObserved=false;molecule.setNetwork('intact',0);receptorParts=[];sequencePage=0;renderSequence();quizAnswer=null;level='primary';stopAudio();$('#subtitle').textContent='';molecule.separated=false;molecule.selected=null;molecule.focus='';molecule.representation='combined';await changeOrganization('monomer',false);molecule.reset();started=false;document.body.classList.add('at-home');molecule.labels=false;$('#landing').hidden=false;await setStation(0);}
function togglePause(){clock.paused=!clock.paused;$('#pause-overlay').hidden=!clock.paused;if(clock.paused)stopAudio();else clock.interact(performance.now());}
function help(){openModal(`<h2>Toma el control</h2><div class="control-columns"><section><h3>Mouse y pantalla táctil</h3><p>Arrastra para rotar. Rueda o pinza con dos dedos para acercar. Botón derecho o dos dedos para desplazar. Pulsa un residuo para seleccionarlo.</p><h3>Teclado</h3><p>WASD / flechas: rotar · + / −: zoom<br>R: centrar · M: precursor / red didáctica<br>X: etiquetas · I: información · F: pantalla completa<br>Espacio: pausa · Escape: cerrar<br>Tab / Mayús+Tab: opciones · Enter: confirmar<br>Ctrl+Mayús+E: modo expositor</p></section><section><h3>Mando de Xbox</h3><p>Palanca izquierda: rotar<br>Palanca derecha: desplazar<br>LT / RT: alejar / acercar<br>Cruceta ← →: estaciones<br>Cruceta ↑ ↓: opciones<br>A: confirmar · B: regresar<br>X: etiquetas · Y: organización<br>LB / RB: representación<br>Menu: pausa · View: centrar</p><button data-action="diagnostics">Abrir diagnóstico del mando</button></section></div><p>Consulta también nuestra ficha técnica impresa.</p><button data-action="sheet">Ver ficha local</button>`,'CONTROLES');}
function settings(){openModal(`<h2>Prepara la exposición</h2><p class="micro">Narraciones ElevenLabs importadas: ${Object.values(audioAvailable).filter(Boolean).length} / ${Object.keys(protein.audios).length}. Si faltan, la sala conserva el texto y puede explicarse en vivo.</p><div class="settings-grid"><label>Volumen <input id="volume" type="range" min="0" max="1" step=".05" value="${volume}"></label><label>Tamaño de texto <select id="text-size"><option value="1">Normal</option><option value="1.12">Grande</option><option value="1.24">Muy grande</option></select></label><label><input id="reduce" type="checkbox" ${reduced?'checked':''}> Reducir animaciones</label><label><input id="permanent" type="checkbox" ${clock.permanent?'checked':''}> Presentación permanente</label><label>Recorrido de esta sala (segundos)<input id="duration" type="number" min="${minTourDuration}" max="600" value="${clock.duration}"></label></div><p>Tras 20 segundos sin interacción comienza un recorrido de ${clock.duration} segundos. Cualquier acción devuelve el control. Los intervalos se ajustan a las narraciones; el mínimo de esta sala es ${minTourDuration} segundos para no cortarlas. El recorrido total de las cuatro salas será configurable; el alcance del tiempo de clase sigue pendiente de la rúbrica.</p><div class="inline-buttons"><button data-action="tour">Iniciar modo museo</button><button data-action="install">Instalar PWA</button><button data-action="diagnostics">Diagnóstico</button><button data-action="presenter">Modo expositor</button></div><p class="micro">Consulta también nuestra ficha técnica impresa.</p><button data-action="sheet">Ver ficha técnica local</button><p class="micro">QR reservado: no hay enlace digital configurado. Puede añadirse después en digitalSheetUrl.</p>`,'ADMINISTRACIÓN');$<HTMLSelectElement>('#text-size').value=localStorage.getItem('museum-text-size')||'1';}
const script=protein.presenterScript;
function presenter(){openModal(`<h2>Guion del equipo <small>60–90 s aprox.</small></h2><p class="script">${script}</p><h3>Preguntas frecuentes y repaso</h3>${protein.questions.map((q,i)=>`<details><summary>${i+1}. ${q.q}</summary><p>${q.explanation}</p></details>`).join('')}<h3>Datos que no deben confundirse</h3><ul>${protein.cautions.map(c=>`<li>${c}</li>`).join('')}</ul><h3>La aplicación</h3>${protein.application.steps.map(s=>`<p><b>${s.title}.</b> ${s.text}</p>`).join('')}<h3>Fuentes consultadas</h3>${sources(protein.sources.map(s=>s.id))}`,'MODO EXPOSITOR · SOLO EQUIPO');}
function diagnostics(){openModal(`<h2>Diagnóstico de entrada</h2><p>Conecta el mando y pulsa A. El movimiento requiere mapeo estándar. Sin mando físico, prueba el simulador: usa las mismas funciones de control.</p><pre id="diag-live"></pre><div class="inline-buttons"><button data-action="calibrate">Calibrar palancas en reposo</button><button data-action="simulate">Activar simulador</button><button data-action="neutral">Soltar simulador</button></div><label>Zona muerta <input id="deadzone" type="range" min=".05" max=".35" step=".01" value="${dz}"></label><div class="sim-sliders">${['Rotar horizontal','Rotar vertical','Desplazar horizontal','Desplazar vertical'].map((t,i)=>`<label>${t}<input data-axis="${i}" type="range" min="-1" max="1" step=".1" value="0"></label>`).join('')}${['LT','RT'].map((t,i)=>`<label>${t}<input data-trigger="${i}" type="range" min="0" max="1" step=".1" value="0"></label>`).join('')}</div><div class="sim-buttons">${Object.entries(buttonMap).map(([n,name])=>`<button data-sim="${n}">${['A','B','X','Y','LB','RB'][Number(n)]||name}</button>`).join('')}</div><button data-action="audit">Comprobar recursos locales</button><p id="audit-results"></p><p class="micro">El simulador comprueba software, no sustituye la prueba física de conectividad, vibración o latencia. FPS mide el bucle con movimiento, no certifica otros equipos.</p>`,'DIAGNÓSTICO');diag=true;}
function focusOption(direction:number){const scope=$<HTMLDialogElement>('#modal').open?$('#modal'):!started?$('#landing'):$('.museum');const options=[...scope.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,summary,a')].filter(e=>e.offsetParent!==null);if(!options.length)return;const index=options.indexOf(document.activeElement as HTMLElement);options[(index+direction+options.length)%options.length].focus();}
function performAction(action:string){if(action!=='pause'&&clock.paused)return;
 switch(action){case'confirm':if(document.activeElement instanceof HTMLElement&&document.activeElement.matches('button,summary'))document.activeElement.click();else if(!started)startExperience();else focusOption(1);break;case'back':if($<HTMLDialogElement>('#modal').open)closeModal();else if(game){game=false;molecule.separated=false;void molecule.load('monomer');renderActivity();}else void setStation(station-1);break;case'labels':labels=!labels;molecule.labels=labels;molecule.applyStyle();updateButtons();break;case'organization':void changeOrganization(toggleOrganization(molecule.organization));break;case'previousRepresentation':case'nextRepresentation':molecule.setRepresentation(reps[(reps.indexOf(molecule.representation)+(action==='nextRepresentation'?1:4))%5]);updateButtons();break;case'reset':molecule.reset();break;case'pause':togglePause();break;case'previousStation':void setStation(station-1);break;case'nextStation':void setStation(station+1);break;case'previousOption':focusOption(-1);break;case'nextOption':focusOption(1);break;}
}
document.addEventListener('click',async event=>{const target=(event.target as HTMLElement).closest<HTMLElement>('button,a');if(!target)return;interaction();
 if(target.dataset.seqpage!==undefined){sequencePage=Number(target.dataset.seqpage);renderSequence();return;}
 if(target.dataset.station){await setStation(Number(target.dataset.station));return;}if(target.dataset.org){await changeOrganization(target.dataset.org as Organization);return;}if(target.dataset.rep){molecule.setRepresentation(target.dataset.rep as Representation);updateButtons();return;}if(target.dataset.focus){molecule.focusRegion(target.dataset.focus);return;}if(target.dataset.residue){selectResidue(target.dataset.residue as ResidueId);return;}if(target.dataset.level){level=target.dataset.level;applyLevel();return;}
 if(target.dataset.build!==undefined){const i=Number(target.dataset.build);if(i>2){$('#game-feedback').textContent='Ese elemento no corresponde: elastina no es una enzima ni un hexámero con zinc.';return;}if(gameDone.includes(String(i))){$('#game-feedback').textContent='Ya identificaste ese elemento.';return;}gameDone.push(String(i));molecule.assemblyProgress=gameDone.length;molecule.applyStyle();renderActivity();if(gameDone.length===3){void vibrate();void playAudio('complete');}return;}
 if(target.dataset.condition){molecule.setNetwork(target.dataset.condition as NetworkCondition,.3);renderActivity();return;}
 if(target.dataset.damageAnswer!==undefined){damageAnswer=Number(target.dataset.damageAnswer);renderActivity();return;}
 if(target.dataset.quiz!==undefined){quizAnswer=Number(target.dataset.quiz);renderActivity();if(quizAnswer===0&&stretchObserved)void vibrate();return;}
 if(target.dataset.step!==undefined){const i=Number(target.dataset.step);if(pathway.includes(i)){$('#path-feedback').textContent=protein.application.steps[i].text;return;}if(i!==pathway.length){$('#path-feedback').textContent='Ese paso viene después. Piensa qué debe ocurrir antes de formar y evaluar el biomaterial.';return;}pathway.push(i);renderActivity();if(i===5)void vibrate();return;}
 if(target.dataset.sim!==undefined){performAction(buttonMap[Number(target.dataset.sim)]);return;}
 switch(target.dataset.action){
 case'jump':{const n=Number($<HTMLInputElement>('#jump-residue').value);if(Number.isInteger(n)&&n>=1&&n<=786)await selectResidue(`A${n}`);else toast('Elige una posición entre 1 y 786.');break;}
 case'confidence':molecule.confidence=!molecule.confidence;molecule.applyStyle();renderActivity();break;
 case'release':molecule.release();stretchObserved=true;renderActivity();break;
 case'start':startExperience();break;case'home':started=false;document.body.classList.add('at-home');molecule.labels=false;molecule.applyStyle();$('#landing').hidden=false;break;case'next':await setStation(station+1);break;case'restart':await restart();break;case'reset-view':molecule.reset();break;case'zoom-in':molecule.zoom(1.15);break;case'zoom-out':molecule.zoom(.87);break;case'labels':performAction('labels');break;case'fullscreen':if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen().catch(()=>toast('Usa F11 para pantalla completa en este navegador.'));break;
 case'help':help();break;case'settings':settings();break;case'presenter':presenter();break;case'diagnostics':diagnostics();break;case'close':closeModal();break;case'pause':togglePause();break;case'details':{const s=protein.stations[station];openModal(`<h2>${s.title.replace('\n',' ')}</h2><p class="lead">${s.detail}</p>${station===3?protein.functionalGroups.map(g=>`<p><b>${g.name}.</b> ${g.text}</p>`).join(''):''}<h3>Evidencia científica</h3>${sources(s.sources)}<p class="micro">Los enlaces externos son consulta opcional. Las explicaciones y modelos de la sala funcionan sin conexión.</p>`);break;}
 case'sound':muted=!muted;$('#sound').textContent=muted?'♪ Audio':'♪ Silenciar';if(muted){stopAudio();$('#subtitle').textContent='';}else {if(!Object.values(audioAvailable).some(Boolean))toast('Narraciones pendientes de importar. Guiones disponibles y texto en pantalla; sin voz sintética de Windows.');void playAudio(protein.stations[station].audio||'intro');}break;
 case'start-game':case'restart-game':await startGame();break;case'compare':await toggleCompare();break;
 case'path-info':openModal(`<h2>De la molécula al biomaterial</h2><p>Representación explicativa. No está a escala y no reproduce un procedimiento clínico ni parámetros de fabricación.</p><div class="path-diagram">${protein.application.steps.map((s,i)=>`<article><span>${i+1} ${s.icon}</span><h3>${s.title}</h3><p>${s.text}</p></article>`).join('')}</div>${sources(protein.application.sourceIds)}`);break;
 case'tour':closeModal();started=true;document.body.classList.remove('at-home');molecule.labels=labels;$('#landing').hidden=true;clock.start=performance.now();clock.paused=false;lastTour=-1;break;case'takeover':interaction();break;
 case'install':if(installPrompt){await installPrompt.prompt();installPrompt=null;}else toast('En Edge o Chrome: menú del navegador → Aplicaciones → Instalar este sitio. La ventana del iniciador ya funciona como app.');break;
 case'sheet':{const missing=await missingResources([protein.printedSheet!]);if(missing.length)toast('La ficha local no está disponible. Consulta la copia impresa.');else openModal(`<h2>Ficha técnica del equipo</h2><p>Consulta también nuestra ficha técnica impresa.</p><a href="${protein.printedSheet}" target="_blank" rel="noopener">Abrir PDF en otra ventana ↗</a><iframe class="pdf-frame" src="${protein.printedSheet}" title="Ficha técnica de elastina"></iframe>`);break;}
 case'calibrate':if(!pad&&!simulating)toast('Conecta un mando o activa el simulador primero.');else{calibration=[];calibrating=true;toast('Suelta las palancas durante un segundo.');}break;
 case'simulate':simulating=true;toast('Simulador activo. Los deslizadores controlan el modelo del fondo.');break;case'neutral':simAxes.fill(0);simTriggers.fill(0);axisSmooth.fill(0);document.querySelectorAll<HTMLInputElement>('[data-axis],[data-trigger]').forEach(x=>x.value='0');break;
 case'audit':{const paths=[...Object.values(protein.models),...Object.entries(protein.audios).filter(([id])=>audioAvailable[id]).map(([,a])=>a.file),'/vendor/3Dmol-min.js','/manifest.webmanifest'];const missing=await missingResources(paths);$('#audit-results').textContent=missing.length?`Faltan: ${missing.join(', ')}`:`✓ ${paths.length} recursos principales disponibles localmente.`;break;}
 }
});
document.addEventListener('input',event=>{interaction();const target=event.target as HTMLInputElement;if(target.id==='stretch'){molecule.setNetwork(molecule.network.condition,Number(target.value));}if(target.id==='volume'){volume=Number(target.value);audio.volume=volume;}if(target.id==='duration'){clock.duration=clamp(Number(target.value)||88,minTourDuration,600);}if(target.id==='deadzone')dz=Number(target.value);if(target.dataset.axis!==undefined){simulating=true;simAxes[Number(target.dataset.axis)]=Number(target.value);}if(target.dataset.trigger!==undefined){simulating=true;simTriggers[Number(target.dataset.trigger)]=Number(target.value);}});
document.addEventListener('change',event=>{const t=event.target as HTMLInputElement;if(t.id==='reduce'){reduced=t.checked;molecule.reduced=reduced;document.documentElement.classList.toggle('reduced',reduced);}if(t.id==='permanent'){clock.permanent=t.checked;if(t.checked){closeModal();started=true;document.body.classList.remove('at-home');molecule.labels=labels;$('#landing').hidden=true;clock.start=performance.now();lastTour=-1;}}if(t.id==='text-size'){document.documentElement.style.setProperty('--text-scale',t.value);localStorage.setItem('museum-text-size',t.value);}});
for(const event of ['pointerdown','pointermove','wheel','touchstart'] as const)document.addEventListener(event,()=>interaction(),{passive:true});
$<HTMLDialogElement>('#modal').addEventListener('cancel',event=>{event.preventDefault();closeModal();});
document.addEventListener('keydown',event=>{interaction();if(event.ctrlKey&&event.shiftKey&&event.code==='KeyE'){event.preventDefault();presenter();return;}if((event.target as HTMLElement).matches('input,select,textarea'))return;if(event.code==='Escape'){if($<HTMLDialogElement>('#modal').open)closeModal();else if(clock.paused)togglePause();return;}if($<HTMLDialogElement>('#modal').open)return;
 const keys:Record<string,()=>void>={KeyW:()=>molecule.rotate(0,-4),ArrowUp:()=>molecule.rotate(0,-4),KeyS:()=>molecule.rotate(0,4),ArrowDown:()=>molecule.rotate(0,4),KeyA:()=>molecule.rotate(-4,0),ArrowLeft:()=>molecule.rotate(-4,0),KeyD:()=>molecule.rotate(4,0),ArrowRight:()=>molecule.rotate(4,0),Equal:()=>molecule.zoom(1.1),NumpadAdd:()=>molecule.zoom(1.1),Minus:()=>molecule.zoom(.9),NumpadSubtract:()=>molecule.zoom(.9),KeyR:()=>molecule.reset(),KeyM:()=>performAction('organization'),KeyX:()=>performAction('labels'),KeyI:()=>document.querySelector<HTMLButtonElement>('[data-action="details"]')!.click(),KeyF:()=>document.querySelector<HTMLButtonElement>('[data-action="fullscreen"]')!.click(),Space:()=>togglePause()};if(keys[event.code]){event.preventDefault();if(!clock.paused||event.code==='Space')keys[event.code]();}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('offline',()=>$('#offline-state').textContent='SIN RED · MODO LOCAL');window.addEventListener('online',()=>$('#offline-state').textContent='RECURSOS LOCALES');
window.addEventListener('gamepadconnected',()=>toast('Mando detectado. Pulsa A para confirmar.'));window.addEventListener('gamepaddisconnected',()=>toast('Mando desconectado. Puedes continuar con mouse o teclado.'));
let previous=performance.now(),diagTime=0;
function tick(now:number){const dt=Math.min((now-previous)/1000,.05);previous=now;frameTimes.push(dt);if(frameTimes.length>90)frameTimes.shift();
 pad=[...(navigator.getGamepads?.()||[])].find(p=>p?.connected)||null;
 const label=pad?pad.mapping==='standard'?'◉ Xbox / mando estándar conectado':'◉ Mando sin mapeo estándar':simulating?'◉ Simulador de mando':'◉ Mouse · teclado · táctil';if(label!==lastPadLabel){$('#pad-status').textContent=label;lastPadLabel=label;}
 const raw=simulating?simAxes:pad?.mapping==='standard'?pad.axes.slice(0,4):[0,0,0,0];
 if(calibrating){calibration.push([...raw]);if(calibration.length>=60){neutral=[0,1,2,3].map(i=>calibration.reduce((s,a)=>s+(a[i]||0),0)/60);calibrating=false;toast('Calibración completada.');}}
 let moved=false;for(let i=0;i<4;i++){axisSmooth[i]=smooth(axisSmooth[i],deadzone((raw[i]||0)-neutral[i],dz),dt);if(Math.abs(axisSmooth[i])>.005)moved=true;}
 const lt=simulating?simTriggers[0]:pad?.mapping==='standard'?pad.buttons[6]?.value||0:0,rt=simulating?simTriggers[1]:pad?.mapping==='standard'?pad.buttons[7]?.value||0:0;
 if((moved||lt>.05||rt>.05)&&!clock.paused){interaction();molecule.rotate(axisSmooth[0]*85*dt,axisSmooth[1]*85*dt);molecule.pan(axisSmooth[2]*100*dt,-axisSmooth[3]*100*dt);if(lt>.05||rt>.05)molecule.zoom(Math.exp((rt-lt)*dt));}
 const buttons=pad?.mapping==='standard'?pad.buttons.map(b=>b.pressed):[];buttons.forEach((pressed,i)=>{if(pressed&&!lastButtons[i]&&buttonMap[i]){interaction();performAction(buttonMap[i]);}});lastButtons=buttons;
 if(!audio.paused&&!audio.ended&&clock.start===null)clock.last=now;
 if(!$<HTMLDialogElement>('#modal').open){const ti=clock.tick(now,protein.tour.steps.length);if(ti>=0){if(!started){started=true;document.body.classList.remove('at-home');molecule.labels=labels;$('#landing').hidden=true;}if(ti!==lastTour){lastTour=ti;const step=protein.tour.steps[ti];void setStation(step.station,true).then(async()=>{if(clock.start===null||lastTour!==ti)return;if(step.organization)await changeOrganization(step.organization,false);if(clock.start===null||lastTour!==ti)return;if(step.focus)molecule.focusRegion(step.focus);void playAudio(`tour-${ti}`);});$('#tour-label').textContent=`RECORRIDO AUTOMÁTICO · ${step.label}`;$('#tour-banner').hidden=false;}if(!reduced)molecule.rotate(6*dt,0,false);if(!clock.permanent&&clock.start!==null&&now-clock.start>=clock.duration*1000){interaction();}}}else clock.last=now;
 if(diag&&now-diagTime>250){diagTime=now;$('#diag-live').textContent=`Mando: ${pad?.id||'Sin mando físico'}\nMapeo: ${pad?.mapping||'—'} · Simulador: ${simulating?'activo':'inactivo'}\nEjes: ${raw.map(v=>v.toFixed(2)).join(' / ')}\nSuavizados: ${axisSmooth.map(v=>v.toFixed(2)).join(' / ')}\nZona muerta: ${dz} · Calibrando: ${calibrating}\nBotones: ${buttons.map((v,i)=>v?i:null).filter(x=>x!==null).join(', ')||'ninguno'}\nLT ${lt.toFixed(2)} · RT ${rt.toFixed(2)}\nBucle: ${Math.round(frameTimes.length/frameTimes.reduce((a,b)=>a+b,0))} FPS`;}
 requestAnimationFrame(tick);
}
async function boot(){try{audioAvailable=await (await fetch('/audio/availability.json')).json();await measureTour();renderSequence();molecule.labels=false;await molecule.load('monomer',false);$('#loading').hidden=true;molecule.viewer.rotate(18,'y');molecule.viewer.rotate(-12,'x');renderStation();document.documentElement.style.setProperty('--text-scale',localStorage.getItem('museum-text-size')||'1');molecule.reduced=reduced;requestAnimationFrame(tick);if('serviceWorker'in navigator&&import.meta.env.PROD){await navigator.serviceWorker.register('/sw.js');const ready=await navigator.serviceWorker.ready;$('#offline-state').textContent=ready.active?'OFFLINE PREPARADO':'PREPARANDO OFFLINE';}}catch(e){$('#loading').innerHTML=`No fue posible iniciar el visor.<br>${esc(String(e))}<br><button onclick="location.reload()">Reintentar</button><p>Comprueba que el navegador tenga aceleración gráfica y abre INICIAR_MUSEO.bat.</p>`;}}
// A narrow diagnostics bridge used by automated integration tests, never to fabricate results.
(window as any).__museum={molecule,clock,getState:()=>({station,gameDone:[...gameDone],firstCys,pathway:[...pathway],receptorParts:[...receptorParts],sequencePage,network:{...molecule.network},stretchObserved,damageAnswer,organization:molecule.organization,selected:molecule.selected,started,quizAnswer,labels}),performAction,selectResidue,getAudioState:()=>({id:audioId,src:audio.currentSrc,time:audio.currentTime,duration:audio.duration,paused:audio.paused,ended:audio.ended,volume:audio.volume,muted}),getFPS:()=>Math.round(frameTimes.length/frameTimes.reduce((a,b)=>a+b,0))};
void boot();

